declare const _default: import("vue").DefineComponent<{}, {
    messageHandlers: any;
    registerMessageHandler: any;
    $emit: (event: "connect" | "chat" | "backBtnClick", ...args: any[]) => void;
    sessionId: string;
    userImage: string | Record<string, any>;
    assistantImage: string | Record<string, any>;
    searchSuggestions: unknown[];
    isSingleVideo: boolean;
    parentQuery: string;
    collectionId: string;
    collectionName: string;
    videoId: string;
    shareUrl: string;
    useCustomAgent: Function;
    $props: {
        readonly sessionId?: string | undefined;
        readonly userImage?: string | Record<string, any> | undefined;
        readonly assistantImage?: string | Record<string, any> | undefined;
        readonly searchSuggestions?: unknown[] | undefined;
        readonly isSingleVideo?: boolean | undefined;
        readonly parentQuery?: string | undefined;
        readonly collectionId?: string | undefined;
        readonly collectionName?: string | undefined;
        readonly videoId?: string | undefined;
        readonly shareUrl?: string | undefined;
        readonly useCustomAgent?: Function | undefined;
    };
}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<import("vue").ExtractPropTypes<{}>>, {}, {}>;
export default _default;
