declare const _default: import("vue").DefineComponent<{}, {
    conversations: any;
    chatLoading: any;
    messageHandlers: {};
    registerMessageHandler: (agentName: any, handler: any) => void;
    addMessage: any;
    $emit: (event: "backBtnClick", ...args: any[]) => void;
    size: string;
    isSingleVideo: boolean;
    userImage: string | Record<string, any>;
    assistantImage: string | Record<string, any>;
    emptyContainerLogo: string | Record<string, any>;
    chatInputPlaceholder: string;
    searchSuggestions: unknown[];
    shareUrl: string;
    customChatHook: Function;
    chatHookConfig: Record<string, any>;
    $props: {
        readonly size?: string | undefined;
        readonly isSingleVideo?: boolean | undefined;
        readonly userImage?: string | Record<string, any> | undefined;
        readonly assistantImage?: string | Record<string, any> | undefined;
        readonly emptyContainerLogo?: string | Record<string, any> | undefined;
        readonly chatInputPlaceholder?: string | undefined;
        readonly searchSuggestions?: unknown[] | undefined;
        readonly shareUrl?: string | undefined;
        readonly customChatHook?: Function | undefined;
        readonly chatHookConfig?: Record<string, any> | undefined;
    };
}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<import("vue").ExtractPropTypes<{}>>, {}, {}>;
export default _default;
